collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.1938775
  brandStrength: 0.5139635
  lightness: 0.8351235
  brandColors:
    - '#D6DEE9'
    - '#1E2213'
    - '#39481D'
    - '#7A6344'
    - '#B29164'
  rhythmicContrast: 0.9394511
typography_spectrum: 0.9242749
layout_spectrum: 0
name: HighHall
