collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1938775
  brandStrength: 0.5139635
  lightness: 0.8351235
  brandColors:
    - '#FFFFFF'
    - '#060606'
    - '#434446'
    - '#7E8285'
    - '#D6D7E2'
  rhythmicContrast: 0
typography_spectrum: 0.9242749
layout_spectrum: 0
name: HighHall
